"""add_includes_and_itinerary_to_tour

Revision ID: 36287374a169
Revises: 84bf0c7f6302
Create Date: 2025-03-09 12:47:10.837512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36287374a169'
down_revision: Union[str, None] = '84bf0c7f6302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('includes', sa.JSON(), nullable=True))
    op.add_column('tours', sa.Column('itinerary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'itinerary')
    op.drop_column('tours', 'includes')
    # ### end Alembic commands ###
